### ISSUE TITLE
Where is your catalog?

### ISSUE THREAD

**Issue by rabernat** [cedadev/cmip6-object-store#39]
@naomi-henderson's [gist](https://gist.github.com/naomi-henderson/4876a860e262c48209f6e981f6d1fe47) for crawling catalogs pointed at this file

https://github.com/cedadev/cmip6-object-store/raw/master/data/cmip6-datasets_2020-10-27.csv.gz

But it appears to be missing.

I think the new version is https://github.com/cedadev/cmip6-object-store/blob/master/catalogs/ceda-zarr-cmip6.csv

However, this doesn't work with the script. So some sort of update to the catalog script is needed.

**Comment by naomi-henderson** [comment]
@rabernat, yes, I will update the script to correspond to their new csv format

**Comment by naomi-henderson** [comment]
@rabernat. Same script will work with two changes:
```
CEDA_cat = 'https://github.com/cedadev/cmip6-object-store/raw/master/catalogs/ceda-zarr-cmip6.csv'
dCEDA = convert_catalog(CEDA_cat, key = 'nc_path', first = 5, last = 14)
```

Well, the upper bounds of some of the plots need to be increased since the number of datasets has grown. 8-)

**Comment by agstephens** [comment]
Hi @naomi-henderson and @rabernat, Note that those files represent our current intake-esm catalog. It points to Zarr files held in our private Object Store - which are currently restricted to access within our firewall. We are working with our admins to get this opened up to the outside world and we anticipate that will happen in the next couple of months.

**Comment by agstephens** [comment]
Closing this one. No ongoing actions captured here.
