### ISSUE TITLE
Create a simple inventory of all datasets to be included

### ISSUE THREAD

**Issue by agstephens** [cedadev/cmip6-object-store#5]
Create a single inventory file of a list of datasets that we should replicate to object store. 

Output should be a text file with one dataset ID per line, e.g.:

```
CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.Amon.zg.gn.v20190710
CMIP6.ScenarioMIP.MPI-M.MPI-ESM1-2-LR.ssp126.r1i1p1f1.CF3hr.psl.gn.v20190815
...
```

Derive the list from the IPCC WG1 priority list. Initially, about 20Tb will be a great start.

**Comment by RuthPetrie** [comment]
[cmip6-datasets.txt](https://github.com/cedadev/cmip6-object-store/files/5237615/cmip6-datasets.txt)

OK I have a list it isn't quite as requested Ag... (sorry) each line has a dataset id, the number of files and the total size of the dataset, I thought this information would be useful and the file can trivially be made into the format you requested. The total here is ~33Tb so a bit more than requested but definitely enough to start with let me know if you want any more work done with this list.

**Comment by agstephens** [comment]
Hi @RuthPetrie , please can you do an update and create a bigger one. Many thanks

**Comment by RuthPetrie** [comment]
@agstephens An updated list of datasets is available at https://github.com/cedadev/cmip6-object-store/blob/master/data/cmip6-datasets_2020-10-27.csv.gz 188.8 TB

**Comment by agstephens** [comment]
Thanks Ruth, that's great!
